### PR TITLE
[WIP] Implementation started for help panel

### PR DESCRIPTION
**Pull request by Siddhi-agg**
Hello @panglesd , As advised by you I have created a PR for the issue #11 so that you can have better review experience. I have marked it as draft since it is still WIP.

### CODE REVIEW

**Comment by Siddhi-agg** [comment]
Also I just noticed that my commit is being pushed through some other user account. I don't have any association or knowledge of the presence of them. I am using SSH in VS-Code to edit and push code through github. 
I have also set the global configuration for my account with these commands.

```
vboxuser@Ubuntu:~/git/diffcessible$ git config --global user.name "Siddhi Agrawal"
vboxuser@Ubuntu:~/git/diffcessible$ git config --global user.email "siddhiagra****l@gmail.com"
```

**Comment by panglesd** [comment]
> I just noticed that my commit is being pushed through some other user account

I have no idea why. The commit info are:

```
Author:     vboxuser <vboxuser@Ubuntu.myguest.virtualbox.org>
AuthorDate: Fri Mar 8 15:16:54 2024 +0530
Commit:     vboxuser <vboxuser@Ubuntu.myguest.virtualbox.org>
CommitDate: Fri Mar 8 15:16:54 2024 +0530
```

Maybe check you ssh key?

**Comment by Siddhi-agg** [comment]
> Maybe check you ssh key?
Not using ssh, I cloned it using https. Maybe I will delete the PR and try again?

**Comment by panglesd** [comment]
It would be much better if the commits were made using your account! But I can't really help on this specific setup, sorry...

**Pull request closed without merging**
